[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "DevTools"
versionNumber = "2.1.9"
description = "In-game developer tools with GUI for Techtonica. Toggle game modes, spawn items, modify player stats, and debug features. Press F8 to open."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-DevTools"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/DevTools.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
